server:
  port: 8080

graphqlio:
  server:
    endpoint: /api/data/graph
    schemaLocationPattern: "**/*.graphql"

## Database Configuration 
spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
# H2 Settings 
  h2:
    console:
      enabled: true
      path: /h2-console

# Data Source Settings 
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE 
    platform: h2